site_description: "Automatic documentation from source, for loudify"
site_url: "https://loudify.readthedocs.io/en/latest/"
repo_url: "https://github.com/martynvdijke/loudify"
edit_uri: "blob/dev/docs/"
repo_name: "martynvdijke/loudify"
site_name: Loudify docs
site_author: "Martyn van Dijke"

theme:
  name: "material"
  favicon: img/favicon.png

plugins:
  - search
  - mkdocstrings