site_name: Loudify docs
site_url: https://example.com/

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
          handlers:
            python:
                setup_commands:
                    - import sys
                    - sys.path.append('../')
                selection:
                    new_path_syntax: true