name: dev build status

on:
  push:
    branches:
      - dev

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: loudify_runner
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name : "Checkout commit"
        uses: actions/checkout@v2
        with:
          ref: dev

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: $

      - name: Install dependencies
        run: |
          make deps

      - name: Run tox
        shell: bash
        working-directory: ${{runner.workspace}}/loudify
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: make tox


